name: multipurpose # ชื่อแอพ
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0  # dependencies พื้นฐานของ flutter 

  # firebase integration
  firebase_core: ^1.10.6 # dependencies พื้นฐานของ firebase
  cloud_firestore: ^3.1.5 # ใช้งาน cloud firestore
  firebase_storage: ^10.2.4 # ใช้งาน firebase storage

  # slidable
  flutter_slidable: ^0.5.7 # ใช้งาน slide ซ้าย ขวา

  # state management
  provider: ^4.3.2+2 # ใช้จัดการข้อมูลต่างๆ

  progress_dialog: ^1.2.4 # ใช้แสดง Loading
  fluttertoast: ^8.0.8 # ใช้แสดงข้อความ
  shared_preferences: ^2.0.6 # ใช้บันทึกข้อมูลแบบ local
  image_picker: ^0.8.4+4 # ใช้เลือกรูปภาพจากเครื่อง
  image_cropper: ^1.4.1 # ใช้ตัดรูป
  intl: ^0.17.0 # จัดการ format ตัวเลข
  date_format: ^2.0.4 # จัดการระบบวันที่
  syncfusion_flutter_charts: ^19.4.50 # ใช้กราฟ

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ # ประกาศใช้งานไฟล์ใน assets